<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * 
     */
    public function run():void
    {

        if(DB::table('products')->get()->count() == 0){
            DB::table('products')->insert(
                array(
                    array('id' => '1','code' => 'frtappc','name' => 'Apple China','hname' => 'सेब चीन','image' => 'apple-china9610.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '2','code' => 'frtban','name' => 'Banana','hname' => 'केला','image' => 'banana4231.jpg','category_id' => '1','unit_id' => '3','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '3','code' => 'frtgua','name' => 'Guava','hname' => 'अमरूद','image' => 'guava-39180.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '4','code' => 'frtman','name' => 'Mango','hname' => 'आम','image' => 'mango5036.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '5','code' => 'frtsap','name' => 'Sapota','hname' => 'चीकू','image' => 'Sapota956.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '6','code' => 'frtorg','name' => 'Orange','hname' => 'संतरा','image' => 'orange1552.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '7','code' => 'frtkiw','name' => 'Kiwi','hname' => 'कीवी','image' => 'kiwi3196.jpg','category_id' => '1','unit_id' => '4','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '8','code' => 'frtche','name' => 'Cherry','hname' => 'चेरी','image' => 'cherry2414.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '9','code' => 'frtcoc','name' => 'Coconut','hname' => 'नारियल','image' => 'coconut1385.jpg','category_id' => '1','unit_id' => '4','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '10','code' => 'frtcra','name' => 'Cranberries','hname' => 'क्रैनबेरी','image' => 'cranberries5806.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '11','code' => 'frtplum','name' => 'Plum','hname' => 'आलूबुखारा','image' => 'damson7941.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '12','code' => 'frtappg','name' => 'Apple Green','hname' => 'हरा सेब','image' => 'apple-green7189.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '13','code' => 'frtappk','name' => 'Apple Kashmir','hname' => 'सेब कश्मीर','image' => 'apple-kashmir3060.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '14','code' => 'frtapps','name' => 'Apple Shimla','hname' => 'सेब शिमला','image' => 'apple-shimla7733.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '15','code' => 'frtappw','name' => 'Apple Washington','hname' => 'सेब वाशिंगटन','image' => 'apple-wasigtan8174.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '16','code' => 'frtapr','name' => 'Apricot','hname' => 'खुबानी','image' => 'apricot-26857.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '17','code' => 'frtcusa','name' => 'Custard Apple','hname' => 'शरीफा','image' => 'custard-apple4915.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '18','code' => 'frtdat','name' => 'Dates','hname' => 'खजूर','image' => 'dates7697.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '19','code' => 'frtdrag','name' => 'Dragon','hname' => 'ड्रैगन फल','image' => 'dragon443.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '20','code' => 'frtpomg','name' => 'Pomegranate','hname' => 'अनार','image' => 'fotolia3348.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '21','code' => 'frtpear','name' => 'Pear','hname' => 'नाशपाती','image' => 'pear4784.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '22','code' => 'frtgrag','name' => 'Grapes Green','hname' => 'हरे अंगूर','image' => 'grapes7334.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '23','code' => 'frtgrab','name' => 'Grapes Black','hname' => 'काले अंगूर','image' => 'grapes-black1332.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '24','code' => 'frtgrar','name' => 'Grapes Red','hname' => 'लाल अंगूर','image' => 'grapes-red9520.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '25','code' => 'frtcocg','name' => 'Coconut Green','hname' => 'हरा नारियल','image' => 'green-coconut3407.jpg','category_id' => '1','unit_id' => '4','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '27','code' => 'frtlem','name' => 'Lemon','hname' => 'नींबू','image' => 'lemon2138.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => NULL,'status' => '1'),
                    array('id' => '28','code' => 'frtlong','name' => 'Longan','hname' => 'पीचू','image' => 'longan274.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '29','code' => 'frtmang','name' => 'Mangosteen','hname' => 'मैंगोस्टीन','image' => 'mangosteens4260.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '30','code' => 'frtmusm','name' => 'Musk Melon','hname' => 'कस्तूरी खरबूज','image' => 'melon2269.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '31','code' => 'frtberr','name' => 'Berry','hname' => 'बेरी','image' => 'Mulberry8890.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '32','code' => 'frtmmp','name' => 'Cantaloupe Melon','hname' => 'खरबूजा','image' => 'musk-melon6555.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '33','code' => 'frtnatp','name' => 'Natal Plum','hname' => 'नेटाल बेर','image' => 'Natal-Plum3463.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '34','code' => 'frtramb','name' => 'Rambutan','hname' => 'रैंबूटन','image' => 'oem-rambutan4468.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '35','code' => 'frtorann','name' => 'Orange Nagpur','hname' => 'संतरा नागपुर','image' => 'orange-nagpur7278.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '36','code' => 'frtpapa','name' => 'Papaya','hname' => 'पपीता','image' => 'papaya6026.jpg','category_id' => '1','unit_id' => '1','default_weight' => '14','weights' => '','status' => '1'),
                    array('id' => '37','code' => 'frtpeac','name' => 'Peach','hname' => 'आडू','image' => 'peach5174.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '38','code' => 'frtpome','name' => 'Pomelo','hname' => 'चकोतरा','image' => 'pemelo2852.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '39','code' => 'frtpin','name' => 'Pineapple (Juice)','hname' => 'अनन्नास','image' => 'pineapple-29485.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '40','code' => 'frtquin','name' => 'Quince','hname' => 'श्रीफल','image' => 'quince7353.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '41','code' => 'frtrasb','name' => 'Raspberry','hname' => 'रसभरी','image' => 'raspberry4852.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '42','code' => 'frtstrb','name' => 'Strawberry','hname' => 'स्ट्रॉबेरी','image' => 'strawberry4898.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '43','code' => 'frtswel','name' => 'Sweet Lime','hname' => 'मौसंबी','image' => 'sweet-lime-24389.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '44','code' => 'frtwatm','name' => 'Water Melon','hname' => 'तरबूज','image' => 'watermelon8186.jpg','category_id' => '1','unit_id' => '1','default_weight' => '14','weights' => '','status' => '1'),
                    array('id' => '45','code' => 'frtzizp','name' => 'Zizyphus','hname' => 'बेर','image' => 'zizyphus2471.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '46','code' => 'frtjamu','name' => 'Jamun','hname' => 'जामुन','image' => 'jamuns2358.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '47','code' => 'frtlych','name' => 'Lychee','hname' => 'लीची','image' => 'Lychee8094.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '48','code' => 'frtmalt','name' => 'Kinnow','hname' => 'किन्नू','image' => 'malta5160.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '49','code' => 'frtpassf','name' => 'Passion Fruit','hname' => 'कृष्णकमल फल','image' => 'Passion9386.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '50','code' => 'frtrosea','name' => 'Rose Apple','hname' => 'जांबूफल','image' => 'Rose-Apple4069.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '51','code' => 'vegamar','name' => 'Amaranths','hname' => 'चौलाई पत्ती','image' => 'amranths3344.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '52','code' => 'vegamla','name' => 'Amla','hname' => 'आमला','image' => 'amla5264.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '53','code' => 'vegashg','name' => 'Ash Gourd','hname' => 'पेठा कद्दू','image' => 'ash-gourd481.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '54','code' => 'vegasp','name' => 'Asparagus','hname' => 'शतावर','image' => 'aspa-gagus4623.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '55','code' => 'vegavoc','name' => 'Avocado','hname' => 'रुचिरा','image' => 'avocado7498.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '56','code' => 'vegbas','name' => 'Basil','hname' => 'तुलसी','image' => 'basil5586.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '57','code' => 'vegbr','name' => 'Beet Root','hname' => 'चुकंदर','image' => 'beet-root3370.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '58','code' => 'vegbl','name' => 'Betel Leaf','hname' => 'पान पत्ता','image' => 'betal-leaf9994.jpg','category_id' => '2','unit_id' => '2','default_weight' => '100','weights' => '','status' => '1'),
                    array('id' => '59','code' => 'vegbg','name' => 'Bitter Gourd','hname' => 'करेला','image' => 'bitter-gourd1565.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '60','code' => 'vegbog','name' => 'Bottle Gourd','hname' => 'लौकी','image' => 'bottle-gourd9997.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '61','code' => 'vegbrin','name' => 'Brinjal','hname' => 'बैंगन','image' => 'brinjal3268.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '62','code' => 'vegbrinl','name' => 'Brinjal long','hname' => 'लंबे बैंगन','image' => 'brinjal-long336.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '63','code' => 'vegbbean','name' => 'Beans Broad','hname' => 'बाकला फली','image' => 'broad-beans1412.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '64','code' => 'vegbroc','name' => 'Broccoli','hname' => 'ब्रोकली','image' => 'broccoli6010.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '65','code' => 'vegcabb','name' => 'Cabbage','hname' => 'पत्ता गोभी','image' => 'cabbage7195.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '66','code' => 'vegcap','name' => 'Capsicum','hname' => 'शिमला मिर्च','image' => 'capsicum-hybrid8352.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '67','code' => 'vegcapy','name' => 'Capsicum Yellow','hname' => 'पीला शिमला मिर्च','image' => 'capsicum-yellow5998.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '68','code' => 'vegcapr','name' => 'Capsicum Red','hname' => 'शिमला मिर्च लाल','image' => 'capsicum-red4501.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '69','code' => 'vegcare','name' => 'Carrot English','hname' => 'अंग्रेजी गाजर','image' => 'carrot-english426.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '70','code' => 'vegcarl','name' => 'Carrot Local','hname' => 'स्थानीय गाजर','image' => 'carrot-local5067.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '71','code' => 'vegcel','name' => 'Celery','hname' => 'अजमोदा','image' => 'celery3195.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '72','code' => 'vegchil','name' => 'Chilli','hname' => 'मिर्च','image' => 'chilli7864.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '73','code' => 'vegchib','name' => 'Chilly Bajji','hname' => 'अचारी मिर्च','image' => 'chilly-bajji8915.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '74','code' => 'vegchch','name' => 'Chow Chow','hname' => 'चाउ चाउ','image' => 'chow-chow5244.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '75','code' => 'vegclu','name' => 'Beans Cluster','hname' => 'गवारफली','image' => 'cluster5704.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '76','code' => 'vegcucb','name' => 'Cucumber Local','hname' => 'खीरा','image' => 'cucumber-local2884.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '77','code' => 'vegcuce','name' => 'Cucumber English','hname' => 'अंग्रेजी खीरा','image' => 'cucumber5317.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '78','code' => 'vegcorl','name' => 'Coriander Leaf','hname' => 'धनिया पत्ती','image' => 'Corinder-leaf684.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '79','code' => 'vegcorn','name' => 'Corn','hname' => 'मक्का','image' => 'corn9544.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '80','code' => 'vegcow','name' => 'Beans Cowpea','hname' => 'लोबिया फली','image' => 'cowpea8762.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '81','code' => 'vegcurl','name' => 'Curry Leaves','hname' => 'कड़ी पत्‍ता','image' => 'curry-leaves376.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '82','code' => 'vegdrus','name' => 'Drumstick','hname' => 'सहजन फली','image' => 'drum-stick9051.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '83','code' => 'vegfenl','name' => 'Fenugreek Leaves','hname' => 'मेथी पत्ते','image' => 'fenugreek-leaves1452.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '84','code' => 'vegfreb','name' => 'Bean French','hname' => 'सेम फली','image' => 'fresho-beans9412.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '85','code' => 'vegging','name' => 'Ginger','hname' => 'अदरक','image' => 'ginger785.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '86','code' => 'vegjackf','name' => 'Jackfruit','hname' => 'कटहल','image' => 'jackfruit2476.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '87','code' => 'vegladf','name' => 'Lady Finger','hname' => 'भिंडी','image' => 'lady-finger1355.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '88','code' => 'vegletl','name' => 'Lettuce Leaf','hname' => 'सलाद पत्ता','image' => 'lettus-green6924.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '89','code' => 'vegmusr','name' => 'Mushroom','hname' => 'मशरूम','image' => 'mashrooms5150.jpg','category_id' => '2','unit_id' => '1','default_weight' => '2','weights' => '','status' => '1'),
                    array('id' => '90','code' => 'vegmint','name' => 'Mint Leaves','hname' => 'पुदीना','image' => 'mint-leaves2205.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '91','code' => 'vegmusg','name' => 'Mustard Greens','hname' => 'सरसों साग','image' => 'mustard-greens8626.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '92','code' => 'vegoni','name' => 'Onion Red','hname' => 'लाल प्याज','image' => 'onion627.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '93','code' => 'vegdreg','name' => 'Oregano','hname' => 'अजवायन पत्ती','image' => 'oregano361.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '94','code' => 'vegpeas','name' => 'Green  Peas','hname' => 'मटर','image' => 'peas808.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '95','code' => 'vegpota','name' => 'Potato Local','hname' => 'देसी आलू ','image' => 'potato984.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '96','code' => 'vegpump','name' => 'Pumpkin','hname' => 'कद्दू','image' => 'pumpkin-green8532.jpg','category_id' => '2','unit_id' => '1','default_weight' => '14','weights' => '','status' => '1'),
                    array('id' => '97','code' => 'vegpumy','name' => 'Pumpkin Yellow','hname' => 'पीला कद्दू','image' => 'pumpkin-yellow7975.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '98','code' => 'vegradi','name' => 'Radish','hname' => 'मूली','image' => 'radish1098.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '99','code' => 'vegrawb','name' => 'Banana Raw','hname' => 'कच्चा केला','image' => 'raw-banana1993.jpg','category_id' => '2','unit_id' => '3','default_weight' => '78','weights' => '','status' => '1'),
                    array('id' => '100','code' => 'vegluffa','name' => 'Luffa','hname' => 'तोरई','image' => 'ridge378.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '101','code' => 'vegspin','name' => 'Spinach','hname' => 'पालक','image' => 'spinach218.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '102','code' => 'vegswep','name' => 'Sweet Potato','hname' => 'शकरकंद','image' => 'sweet-potato5435.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '103','code' => 'vegtama','name' => 'Tamarind','hname' => 'इमली','image' => 'tamarind7185.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '104','code' => 'vegtoma','name' => 'Tomato Desi','hname' => 'देसी टमाटर','image' => 'Tomato3220.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '105','code' => 'vegmurn','name' => 'Turnip','hname' => 'शलजम','image' => 'turnip13522.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '106','code' => 'vegyam','name' => 'Yam','hname' => 'जिमीकंद','image' => 'yam4937.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '107','code' => 'vegcauf','name' => 'Cauliflower','hname' => 'फूलगोभी','image' => 'CauliFlower2811.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '108','code' => 'veggarli','name' => 'Garlic','hname' => 'लहसुन','image' => 'Garlic5850.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '109','code' => 'vegmixs','name' => 'Mix Sprouts','hname' => 'मिक्स अंकुरित','image' => 'Sprouts4931.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '110','code' => 'vegtinda','name' => 'Tinda','hname' => 'टिंडा','image' => 'tinda4610.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '111','code' => 'vegrawm','name' => 'Mango Raw','hname' => 'कच्चा आम','image' => 'raw-mango6759.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '112','code' => 'vegrawp','name' => 'Papaya Raw','hname' => 'कच्चा पपीता','image' => 'papaya-raw2395.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '113','code' => 'vegkach','name' => 'Kachalu','hname' => 'कचालू','image' => 'Kachalu2084.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '114','code' => 'veglotr','name' => 'Lotus Root','hname' => 'कमल ककडी','image' => 'lotus-root695.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '115','code' => 'vegcabr','name' => 'Cabbage Red','hname' => 'लाल पत्ता गोभी','image' => 'cabbage-red534.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '116','code' => 'vegkaro','name' => 'Karonda','hname' => 'करोंदा','image' => 'Karonda2653.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '117','code' => 'frtgalgal','name' => 'Galgal','hname' => 'गलगल','image' => 'galgal5934.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '118','code' => 'vegtmth','name' => 'Tomato Hybrid','hname' => 'हाइब्रिड टमाटर','image' => 'hybrid-tomato605.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '119','code' => 'frtdsrm','name' => 'Mango Dusehri','hname' => 'दशहरी आम','image' => 'mango-dusehri1687.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '120','code' => 'frtksrm','name' => 'Mango Kesar','hname' => 'केसर आम','image' => 'mango-kesar2124.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '121','code' => 'frtsmlm','name' => 'Mango Small','hname' => 'छोटा आम','image' => 'mango-small5921.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '122','code' => 'vegony','name' => 'Onion Nasik','hname' => 'नासिक प्याज','image' => 'onion_yellow2793.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '123','code' => 'vegruspot','name' => 'Russet Potato','hname' => 'पहाड़ी आलू','image' => 'russet-potato1312.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '124','code' => 'frtbg','name' => 'Babugosha','hname' => 'बब्बूगोशा','image' => 'babugosha2022.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '125','code' => 'arbvegt','name' => 'Arbi','hname' => 'अरबी','image' => 'arbi22572.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '126','code' => 'chnfrt','name' => 'Mango Chaunsa','hname' => 'आम चोशा','image' => 'Chounsa9310.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '127','code' => 'srdfrt','name' => 'Sarda','hname' => 'शारदा','image' => 'sarda1876.jpg','category_id' => '1','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '128','code' => 'vegrigd','name' => 'Ridge Gourd','hname' => 'तुरई','image' => 'kali-tori9564.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '129','code' => 'vegbrj','name' => 'Brinjal Small','hname' => ' छोटा बैंगन','image' => 'brinjal-small2744.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '130','code' => 'frozveg','name' => 'Frozen Peas','hname' => 'फरोजन मटर','image' => 'frozen peas17077.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '131','code' => 'vegcallo','name' => 'Cauliflower local','hname' => 'स्थानीय फूलगोभी','image' => 'cauli-local3017.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1'),
                    array('id' => '132','code' => 'vegfpea','name' => 'Frozen peas','hname' => ' जमे हुए मटर','image' => 'frozen-peas1528.jpg','category_id' => '2','unit_id' => '1','default_weight' => '1','weights' => '','status' => '1')
                )
            );
        } else {
            echo "Table is not empty, therefore NOT ";
        }
    }
}
