<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;


class SellerDatabase extends Model
{

    protected $fillable = ['name','seller_id','status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        /*static::addGlobalScope('status', function (Builder $builder){
            $builder->where('status', true);
        });*/
    }
    protected $casts = [
        'status' => 'boolean'
    ];
    public function seller(){
        return $this->belongsTo(Seller::class);
    }
}
