<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = ['name', 'category_id', 'status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        /*static::addGlobalScope('status', function (Builder $builder){
            $builder->where('status', true);
        });*/
    }
    protected $casts = [
        'status' => 'boolean'
    ];

    public function category(){
        return $this->belongsTo(Category::class);
    }
}
